/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './__root'
import { Route as SignupImport } from './signup'
import { Route as LoginImport } from './login'
import { Route as LibraryImport } from './library'
import { Route as IndexImport } from './index'
import { Route as SubmissionSubmissionIdImport } from './submission.$submissionId'
import { Route as ModuleCreateImport } from './module/create'
import { Route as QuizViewQuizIdImport } from './quiz/view.$quizId'
import { Route as QuizSessionQuizIdImport } from './quiz/session.$quizId'
import { Route as ModuleViewModuleIdImport } from './module/view.$moduleId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LibraryRoute = LibraryImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SubmissionSubmissionIdRoute = SubmissionSubmissionIdImport.update({
  id: '/submission/$submissionId',
  path: '/submission/$submissionId',
  getParentRoute: () => rootRoute,
} as any)

const ModuleCreateRoute = ModuleCreateImport.update({
  id: '/module/create',
  path: '/module/create',
  getParentRoute: () => rootRoute,
} as any)

const QuizViewQuizIdRoute = QuizViewQuizIdImport.update({
  id: '/quiz/view/$quizId',
  path: '/quiz/view/$quizId',
  getParentRoute: () => rootRoute,
} as any)

const QuizSessionQuizIdRoute = QuizSessionQuizIdImport.update({
  id: '/quiz/session/$quizId',
  path: '/quiz/session/$quizId',
  getParentRoute: () => rootRoute,
} as any)

const ModuleViewModuleIdRoute = ModuleViewModuleIdImport.update({
  id: '/module/view/$moduleId',
  path: '/module/view/$moduleId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/module/create': {
      id: '/module/create'
      path: '/module/create'
      fullPath: '/module/create'
      preLoaderRoute: typeof ModuleCreateImport
      parentRoute: typeof rootRoute
    }
    '/submission/$submissionId': {
      id: '/submission/$submissionId'
      path: '/submission/$submissionId'
      fullPath: '/submission/$submissionId'
      preLoaderRoute: typeof SubmissionSubmissionIdImport
      parentRoute: typeof rootRoute
    }
    '/module/view/$moduleId': {
      id: '/module/view/$moduleId'
      path: '/module/view/$moduleId'
      fullPath: '/module/view/$moduleId'
      preLoaderRoute: typeof ModuleViewModuleIdImport
      parentRoute: typeof rootRoute
    }
    '/quiz/session/$quizId': {
      id: '/quiz/session/$quizId'
      path: '/quiz/session/$quizId'
      fullPath: '/quiz/session/$quizId'
      preLoaderRoute: typeof QuizSessionQuizIdImport
      parentRoute: typeof rootRoute
    }
    '/quiz/view/$quizId': {
      id: '/quiz/view/$quizId'
      path: '/quiz/view/$quizId'
      fullPath: '/quiz/view/$quizId'
      preLoaderRoute: typeof QuizViewQuizIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/module/create': typeof ModuleCreateRoute
  '/submission/$submissionId': typeof SubmissionSubmissionIdRoute
  '/module/view/$moduleId': typeof ModuleViewModuleIdRoute
  '/quiz/session/$quizId': typeof QuizSessionQuizIdRoute
  '/quiz/view/$quizId': typeof QuizViewQuizIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/module/create': typeof ModuleCreateRoute
  '/submission/$submissionId': typeof SubmissionSubmissionIdRoute
  '/module/view/$moduleId': typeof ModuleViewModuleIdRoute
  '/quiz/session/$quizId': typeof QuizSessionQuizIdRoute
  '/quiz/view/$quizId': typeof QuizViewQuizIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/module/create': typeof ModuleCreateRoute
  '/submission/$submissionId': typeof SubmissionSubmissionIdRoute
  '/module/view/$moduleId': typeof ModuleViewModuleIdRoute
  '/quiz/session/$quizId': typeof QuizSessionQuizIdRoute
  '/quiz/view/$quizId': typeof QuizViewQuizIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/login'
    | '/signup'
    | '/module/create'
    | '/submission/$submissionId'
    | '/module/view/$moduleId'
    | '/quiz/session/$quizId'
    | '/quiz/view/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/login'
    | '/signup'
    | '/module/create'
    | '/submission/$submissionId'
    | '/module/view/$moduleId'
    | '/quiz/session/$quizId'
    | '/quiz/view/$quizId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/login'
    | '/signup'
    | '/module/create'
    | '/submission/$submissionId'
    | '/module/view/$moduleId'
    | '/quiz/session/$quizId'
    | '/quiz/view/$quizId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ModuleCreateRoute: typeof ModuleCreateRoute
  SubmissionSubmissionIdRoute: typeof SubmissionSubmissionIdRoute
  ModuleViewModuleIdRoute: typeof ModuleViewModuleIdRoute
  QuizSessionQuizIdRoute: typeof QuizSessionQuizIdRoute
  QuizViewQuizIdRoute: typeof QuizViewQuizIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ModuleCreateRoute: ModuleCreateRoute,
  SubmissionSubmissionIdRoute: SubmissionSubmissionIdRoute,
  ModuleViewModuleIdRoute: ModuleViewModuleIdRoute,
  QuizSessionQuizIdRoute: QuizSessionQuizIdRoute,
  QuizViewQuizIdRoute: QuizViewQuizIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/library",
        "/login",
        "/signup",
        "/module/create",
        "/submission/$submissionId",
        "/module/view/$moduleId",
        "/quiz/session/$quizId",
        "/quiz/view/$quizId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/library": {
      "filePath": "library.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/module/create": {
      "filePath": "module/create.tsx"
    },
    "/submission/$submissionId": {
      "filePath": "submission.$submissionId.tsx"
    },
    "/module/view/$moduleId": {
      "filePath": "module/view.$moduleId.tsx"
    },
    "/quiz/session/$quizId": {
      "filePath": "quiz/session.$quizId.tsx"
    },
    "/quiz/view/$quizId": {
      "filePath": "quiz/view.$quizId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
